// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static late final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_WEB']!,
    appId: '1:179007539739:web:c5bad7f299fcef6090c6be',
    messagingSenderId: '179007539739',
    projectId: 'chatting-4faf6',
    authDomain: 'chatting-4faf6.firebaseapp.com',
    databaseURL: 'https://chatting-4faf6-default-rtdb.firebaseio.com',
    storageBucket: 'chatting-4faf6.firebasestorage.app',
    measurementId: 'G-7DPVXGP26Z',
  );

  static late final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_AND']!,
    appId: '1:179007539739:android:03b6e363c2d1863290c6be',
    messagingSenderId: '179007539739',
    projectId: 'chatting-4faf6',
    databaseURL: 'https://chatting-4faf6-default-rtdb.firebaseio.com',
    storageBucket: 'chatting-4faf6.firebasestorage.app',
  );

  static late final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_IOS']!,
    appId: '1:179007539739:ios:3afe53996af4ea9890c6be',
    messagingSenderId: '179007539739',
    projectId: 'chatting-4faf6',
    databaseURL: 'https://chatting-4faf6-default-rtdb.firebaseio.com',
    storageBucket: 'chatting-4faf6.firebasestorage.app',
    iosBundleId: 'com.example.adminUser',
  );

  static late final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_MAC']!,
    appId: '1:179007539739:ios:3afe53996af4ea9890c6be',
    messagingSenderId: '179007539739',
    projectId: 'chatting-4faf6',
    databaseURL: 'https://chatting-4faf6-default-rtdb.firebaseio.com',
    storageBucket: 'chatting-4faf6.firebasestorage.app',
    iosBundleId: 'com.example.adminUser',
  );

  static late final FirebaseOptions windows = FirebaseOptions(
    apiKey:dotenv.env['API_KEY_WIN']!,
    appId: '1:179007539739:web:30319949f6af8e6790c6be',
    messagingSenderId: '179007539739',
    projectId: 'chatting-4faf6',
    authDomain: 'chatting-4faf6.firebaseapp.com',
    databaseURL: 'https://chatting-4faf6-default-rtdb.firebaseio.com',
    storageBucket: 'chatting-4faf6.firebasestorage.app',
    measurementId: 'G-NQ9LGGPN8T',
  );
}
